package com.example.colores.model

class ColorModel {
    var listaColores = mutableListOf<MiColor>(
        MiColor("#F0F8FF", "aliceblue"),
        MiColor("#FAEBD7", "antiquewhite"),
        MiColor("#00FFFF", "aqua"),
        MiColor("#7FFFD4", "aquamarine"),
        MiColor("#F0FFFF", "azure"),
        MiColor("#F5F5DC", "beige"),
        MiColor("#FFE4C4", "bisque"),
        MiColor("#000000", "black"),
        MiColor("#FFEBCD", "blanchedalmond"),
        MiColor("#0000FF", "blue"),
        MiColor("#8A2BE2", "blueviolet"),
        MiColor("#A52A2A", "brown"),
        MiColor("#DEB887", "burlywood"),
        MiColor("#5F9EA0", "cadetblue"),
        MiColor("#7FFF00", "chartreuse"),
        MiColor("#D2691E", "chocolate"),
        MiColor("#FF7F50", "coral"),
        MiColor("#6495ED", "cornflowerblue"),
        MiColor("#FFF8DC", "cornsilk"),
        MiColor("#DC143C", "crimson"),
        MiColor("#00FFFF", "cyan"),
        MiColor("#00008B", "darkblue"),
        MiColor("#008B8B", "darkcyan"),
        MiColor("#B8860B", "darkgoldenrod"),
        MiColor("#A9A9A9", "darkgray"),
        MiColor("#006400", "darkgreen"),
        MiColor("#BDB76B", "darkkhaki"),
        MiColor("#8B008B", "darkmagenta"),
        MiColor("#556B2F", "darkolivegreen"),
        MiColor("#FF8C00", "darkorange"),
        MiColor("#9932CC", "darkorchid"),
        MiColor("#8B0000", "darkred"),
        MiColor("#E9967A", "darksalmon"),
        MiColor("#8FBC8F", "darkseagreen"),
        MiColor("#483D8B", "darkslateblue"),
        MiColor("#2F4F4F", "darkslategray"),
        MiColor("#00CED1", "darkturquoise"),
        MiColor("#9400D3", "darkviolet"),
        MiColor("#FF1493", "deeppink"),
        MiColor("#00BFFF", "deepskyblue"),
        MiColor("#696969", "dimgray"),
        MiColor("#1E90FF", "dodgerblue"),
        MiColor("#B22222", "firebrick"),
        MiColor("#FFFAF0", "floralwhite"),
        MiColor("#228B22", "forestgreen"),
        MiColor("#FF00FF", "fuchsia"),
        MiColor("#DCDCDC", "gainsboro"),
        MiColor("#F8F8FF", "ghostwhite"),
        MiColor("#FFD700", "gold"),
        MiColor("#DAA520", "goldenrod"),
        MiColor("#808080", "gray"),
        MiColor("#008000", "green"),
        MiColor("#ADFF2F", "greenyellow"),
        MiColor("#F0FFF0", "honeydew"),
        MiColor("#FF69B4", "hotpink"),
        MiColor("#CD5C5C", "indianred"),
        MiColor("#4B0082", "indigo"),
        MiColor("#FFFFF0", "ivory"),
        MiColor("#F0E68C", "khaki"),
        MiColor("#E6E6FA", "lavender"),
        MiColor("#FFF0F5", "lavenderblush"),
        MiColor("#7CFC00", "lawngreen"),
        MiColor("#FFFACD", "lemonchiffon"),
        MiColor("#ADD8E6", "lightblue"),
        MiColor("#F08080", "lightcoral"),
        MiColor("#E0FFFF", "lightcyan"),
        MiColor("#FAFAD2", "lightgoldenrodyellow"),
        MiColor("#D3D3D3", "lightgray"),
        MiColor("#90EE90", "lightgreen"),
        MiColor("#FFB6C1", "lightpink"),
        MiColor("#FFA07A", "lightsalmon"),
        MiColor("#20B2AA", "lightseagreen"),
        MiColor("#87CEFA", "lightskyblue"),
        MiColor("#778899", "lightslategray"),
        MiColor("#B0C4DE", "lightsteelblue"),
        MiColor("#FFFFE0", "lightyellow"),
        MiColor("#00FF00", "lime"),
        MiColor("#32CD32", "limegreen")
    )

    public suspend fun devolverLista() : Datos {
        return Datos("ok", listaColores)
    }
}